addSbtPlugin("com.typesafe.play" %% "sbt-plugin" % "2.7.3")
addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("rocks.muki" %% "sbt-graphql" % "0.12.0")
addSbtPlugin("org.scoverage" %% "sbt-scoverage" % "1.5.1")
addSbtPlugin("com.eed3si9n" %% "sbt-buildinfo" % "0.7.0")